### PR TITLE
Use app grid icon

### PR DESCRIPTION
**Pull request by godlyranchdressing**
Use the regular app grid icon seen in #134

### CODE REVIEW

**Comment by godlyranchdressing** [comment]
@Feichtmeier Sorry, I'm confused. What other icons?

**Comment by Feichtmeier** [comment]
Didn't want to make a review and cancel this.
Let me try this first please

**Comment by Feichtmeier** [comment]
Just tried it: please dont change the background this looks strange:
screenshot from 2018-04-27 20-04-00
Other than that we could keep the grid until the designers jump in and want to revert? They are pretty afk atm

**Comment by godlyranchdressing** [comment]
@Feichtmeier Oh, you make a good point there. The background is so that it won't get lost in a light wallpaper. I personally think the panel and dash transparency is way too high which is what prompted the background on the button, but I know I'm mostly alone on that one.

**Comment by Feichtmeier** [comment]
Let's try it without the black background, I think we can still see the dots pretty good. I'll try again then? We are pretty much alone online xD

**Comment by madsrh** [comment]
@Feichtmeier It is not up to us. @didrocks will know if we can keep the Ubuntu logo or we have to follow upstream, but you're right that it's a huge set back for branding. I would prefer to keep the logo as Windows and OSX does.

**Comment by ya-d** [comment]
From a usability/UX standpoint I think this is quite a bit different to macOS or Windows. macOS uses the Apple logo for it's system menu (About, Settings, App Store, Power, …), Windows uses its own logo for the "start" menu (Files, Settings, Power **+** Apps). While "Show Applications" is, well, just that: an app overview. So while the brand logo could be related to "the system" in general, I fail to see the relation of the Ubuntu logo in Communitheme to anything Ubuntu. I really get the desire for branding and it sure looks good, but I think it could hinder discoverability. (Where are my apps? … Sure, users will remember somehow and get used to it, but it doesn't make sense or provide a meaning to me.)

So maybe the "better" place for Ubuntu branding would be Activities ("the system" provides workspaces and window management) or system menu (obviously). But top left/right is far less from ideal for design of course. But maybe someone comes up with a valuable solution?!

**Comment by madsrh** [comment]
@ya-d What I meant was that I would like to see the logo on the desktop, so when you see a screenshot you'll know that this is Ubuntu, **like you can with Windows and Mac** 😉 

I agree that _Activities_ might be a better fit - that has [also been discussed](https://community.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/492) but I think, just like the app grid icon, we'll have to follow upstream.

didrocks is tagged above so let's see what he replies, but I'm sure this issue has been addressed by the design team as a bug earlier.

**Comment by Feichtmeier** [comment]
@madsrh @luxamman 
IF we keep the ubuntu button, what do you think of this very unity8 approach on the button:
(pretty easy change in the code):
screenshot from 2018-05-01 19-05-58

**Comment by Feichtmeier** [comment]
Alright was just an idea - totally reasonable. Some things look nice on the first or even the 10th look but start to burn your eyes after some weeks

**Comment by mivoligo** [comment]
My 2 cents as a new Gnome Shell user: 
In Unity clicking "Ubuntu" icon did the same as hitting the "super" key on the keyboard. In GS it doesn't work like that. So I think the good option would be to put Ubuntu logo next to Activities to hint what selecting "super" key does and keeping a bit of Ubuntu branding.

**Comment by godlyranchdressing** [comment]
I think having the Ubuntu icon next to Activities and also having the currently focused window's icon immediately after can have that area look a little busy.

**Comment by clobrano** [comment]
That's right, but I still prefer it to having ubuntu logo at the bottom of the dock

**Comment by Feichtmeier** [comment]
What about this? Shall I push the changes in a separate PR and we close this? @clobrano @godlyranchdressing

**Comment by Feichtmeier** [comment]
As discussed with @didrocks on the hub, we migrate this to the gtk repo

**Pull request closed without merging**
