### PR TITLE
Refine active apps in dash grid

### PR DESCRIPTION
**Pull request by Feichtmeier**
Solution to https://github.com/ubuntu/gnome-shell-communitheme/issues/114

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gnome-shell-communitheme-pr128`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gnome-shell-communitheme-pr128` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by madsrh** [comment]
@Feichtmeier Hmmm, nothing happens when I test the snap 🤔 Just as I was praising snaps 😆

**Comment by Feichtmeier** [comment]
Sorry... this was too late. One moment please...

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gnome-shell-communitheme-pr128`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gnome-shell-communitheme-pr128` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
What do you think about dots' size? Jokes apart, I agree with @NusiNusi, they are too little to spot

**Comment by NusiNusi** [comment]
The Icons are bigger in the app-view so the dots should be bigger too. Would that work? Lets say the icon-size is doubled could we double the dot-size? Would that look good?

**Comment by Feichtmeier** [comment]
Ha! :cowboy_hat_face: 
image
Well.... there remains one problem.... the length of the app name :( If you got really long app names the dot should adapt to that shouldnt it?

**Comment by clobrano** [comment]
I think it depends if you set the dot with kind of absolute position or relative.
However if we have doubts, maybe we can just keep the safer solution?

**Comment by Feichtmeier** [comment]
Well I know now how I negotiate the margin in _dock.scss... By adding
.app-well-app-running-dot {
      margin-right: 0px;
    }

Anyways, I think none of ALL solutions looks as good as the current thing in master. 
When I increase the dot then the transparent selection squircle's border is almost at the edge of the dot. It all looks crappy :|

**Comment by madsrh** [comment]
@Feichtmeier nice work but a bit sad. I was really hoping [this one](https://user-images.githubusercontent.com/15329494/39263306-0c3fbb0e-48c2-11e8-83ec-28f5ed1cd316.png) could be work 😞

**Comment by Feichtmeier** [comment]
Well, when the more experienced scss/css users here *staring and carlo and aaron* would explain to me how I can set the margin-right property in run time we could make it work

**Comment by Feichtmeier** [comment]
@madsrh how about this rounded line:
peek 2018-04-25 20-40

**Comment by NusiNusi** [comment]
YESS! Would it be possible to make all the other lines as rounded as these ones?

**Comment by Feichtmeier** [comment]
Ahh forget about the word "rounded" there is no border-radius at this thickness. This would be absolutely on par with all the other lines we use. 2px. Imho we could use this or just close this PR and use the current one. The dots don't cut it with these limitations (maybe it's limited by me, so we could close this PR and let the issue opened until aaron or carlo have time for this :meme:ain't nobody got time for this)

**Comment by clobrano** [comment]
> Well, wh en the more experienced scss/css users here staring and carlo and aaron would explain to me how I can set the margin-right property in run time we could make it work

I bet you didn't read my interview :grinning: 
However, I don't actually know how to set it properly. I tried to move the dot at label side, but got the same problem, since the position of the dot is fixed (as far as I can see).

About the use of underlines, we use it everywhere to show selection, and this is not, so I am not convinced.

**Comment by madsrh** [comment]
> About the use of underlines, we use it everywhere to show selection, and this is not, so I am not convinced.

@clobrano +1

I'll just tag @nana-4 and @godlyranchdressing. Let's hope they can work their magic :sparkles:

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gnome-shell-communitheme-pr128`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gnome-shell-communitheme-pr128` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
@madsrh @luxamman what about this:
screenshot from 2018-04-27 12-44-26

**Comment by Luxamman** [comment]
Overall I would prefer to see a similarity to the active apps in the dock - so the user doesn't have to rethink what that means. Also, it could be confused with folders. So for me it could be just a simple orange dot under the app name. That's maybe not too present, but I also don't need it to be, because I have all of my open apps in the dock.

**Comment by madsrh** [comment]
I agree with @Luxamman.

> I'll just tag @nana-4 and @godlyranchdressing. Let's hope they can work their magic ✨

I'm still hoping for [this](https://user-images.githubusercontent.com/15329494/39263306-0c3fbb0e-48c2-11e8-83ec-28f5ed1cd316.png) 😄

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gnome-shell-communitheme-pr128`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gnome-shell-communitheme-pr128` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
Hm, I realized (2 days later) that adwaita uses the same line in the dock :octopus: 
Let me try the bottom Dot again before we cancel this

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gnome-shell-communitheme-pr128`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gnome-shell-communitheme-pr128` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by madsrh** [comment]
I'm adding a +1 for this BUT I would much rather if we could (as mentioned) have [the dot to the side of the text](https://user-images.githubusercontent.com/15329494/39263306-0c3fbb0e-48c2-11e8-83ec-28f5ed1cd316.png). I say let's go with this one until @godlyranchdressing or @nana-4 returns and hopefully has the answer 😄

@Feichtmeier would it be possible to add a very subtle shadow to the dot? It's kind of hard to spot

**Comment by Feichtmeier** [comment]
Closing this as I had a stupid moment and mixed branches ... Discussion continues here:https://github.com/ubuntu/gnome-shell-communitheme/pull/149

**Pull request closed without merging**
