### PR TITLE
Flat_calendar_clear_btn_&_dot_as_active_app_indicator

### PR DESCRIPTION
**Pull request by Feichtmeier**
Imported the wrong button in the previous PR - just a correction
Merged the Dot in app grid into this (sorry)

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gnome-shell-communitheme-pr149`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gnome-shell-communitheme-pr149` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
@madsrh like this?:
image

**Comment by madsrh** [comment]
@Feichtmeier Hard to tell with your wallpaper 😆 It looks like a white glow behind the dot. I meant something like this:
image

**Comment by Feichtmeier** [comment]
screenshot from 2018-04-30 15-59-26
box-shadow: 1px 1px 5px 0px transparentize(black, 0.5);
@madsrh like this? you can try sth here: https://www.cssmatic.com/box-shadow

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gnome-shell-communitheme-pr149`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gnome-shell-communitheme-pr149` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by madsrh** [comment]
Perfect! 🎊

**Pull request merged**
