### PR TITLE
white_shell_&_notification_icon_improvements

### PR DESCRIPTION
**Pull request by Feichtmeier**
Fix white shell audio popup & notification icons

peek 2018-05-04 23-04

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gnome-shell-communitheme-pr166`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gnome-shell-communitheme-pr166` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
peek 2018-05-04 18-41

peek 2018-05-04 18-43

@clobrano @madsrh @godlyranchdressing 
You already posted in the wrong "thread!!!!! :laughing:  What do you say? Feels more intuitive imho

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gnome-shell-communitheme-pr166`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gnome-shell-communitheme-pr166` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gnome-shell-communitheme-pr166`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gnome-shell-communitheme-pr166` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by madsrh** [comment]
Hey 👋 
The Alt+tab was so gorgeous in the dark version, but I don't think the current white version is working. It's the white text on light gray background. Would something like this be possible?
image

**Comment by Feichtmeier** [comment]
No that's not possible.  But this:
- darkened the selection by 10% more
- increased font weight of the white text
peek 2018-05-04 23-41

**Pull request merged**
