### PR TITLE
Notification button active border bleed fix +  transparency

### PR DESCRIPTION
**Pull request by Feichtmeier**
screenshot from 2018-04-26 22-46-39
screenshot from 2018-04-26 22-46-26
peek 2018-04-26 22-35
@godlyranchdressing could you help me with one more thing: the symbolic notification icons have a very light color and I can't find the property to change it :grin: 
image

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gnome-shell-communitheme-pr136`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gnome-shell-communitheme-pr136` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gnome-shell-communitheme-pr136`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gnome-shell-communitheme-pr136` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gnome-shell-communitheme-pr136`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gnome-shell-communitheme-pr136` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gnome-shell-communitheme-pr136`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gnome-shell-communitheme-pr136` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gnome-shell-communitheme-pr136`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gnome-shell-communitheme-pr136` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
@madsrh okay I flipped it: slight transparent in normal and solid white on hover!

HOWEVER!!! @godlyranchdressing I am almost crying :cry: 

There are notifications that have two buttons and there are ones that have only 1 button.
When I change the border radius of the .notification-button it works with 1 button but not with two buttons When I change the border radius of the first child and last child it works with 2 buttons but not with 1 button :rage: 

.notification-button {
    min-height: 35px;
    padding: 0 16px;
    background-color: transparent;
    color: $inkstone;
    font-weight: 500;
    &:active { background-color: rgba(0, 0, 0, 0.26); border-radius: 0 0 $medium-radius $medium-radius;}
    &:first-child:active{ border-radius: 0 0 0 $medium-radius; }
    &:last-child:active{ border-radius: 0 0 $medium-radius 0 ;}
  }

2buttons
1buttonwithbleed

__________

.notification-button {
    min-height: 35px;
    padding: 0 16px;
    background-color: transparent;
    color: $inkstone;
    font-weight: 500;
    &:active { background-color: rgba(0, 0, 0, 0.26); border-radius: 0 0 $medium-radius $medium-radius;}
    //&:first-child:active{ border-radius: 0 0 0 $medium-radius; }
    //&:last-child:active{ border-radius: 0 0 $medium-radius 0 ;}
  }

borderworks1button
bordersucks2buttons

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gnome-shell-communitheme-pr136`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gnome-shell-communitheme-pr136` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by PlugaruT** [comment]
Hey @Feichtmeier can you please tell what have you used to make those tray icons to look somehow of constant height? By default they look ugly and also not all of them are of the same width. Thanks.

Sorry for offtopic.

**Comment by godlyranchdressing** [comment]
@Feichtmeier maybe:
```
.notification-button {
    &:first-child { &, &:active { border-radius: 0 0 0 $medium-radius; } }
    &:last-child { &, &:active { border-radius: 0 0 $medium-radius 0; } }
}
```
?

I don't know if the :active is needed but I'll assume it is. If you want, I can make another PR and do something similar to what I did with #135, importing the gtk colors, using buttons that look like the gtk theme's buttons, etc. only with notifications.

**Comment by Feichtmeier** [comment]
Hm that could have done the trick:
screenshot from 2018-04-27 20-11-46
Let's merge this

**Comment by Feichtmeier** [comment]
@godlyranchdressing you know what's really strange? Upstream doesn't do any additional magic:
https://github.com/GNOME/gnome-shell/blob/master/data/theme/gnome-shell-sass/_common.scss#L1529
I wonder if they got this problem, too. Cant check because I have no gnome-session installed.... let me check

**Comment by Feichtmeier** [comment]
@godlyranchdressing holy sh*t. I did it. Imported the button functions now this horror has an end

**Comment by godlyranchdressing** [comment]
@Feichtmeier Should we use $light_button_bg_color for consistency's sake though? I imported the gtk colors in my last commit. The button mixin still needs to be updated too, though.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gnome-shell-communitheme-pr136`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gnome-shell-communitheme-pr136` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gnome-shell-communitheme-pr136`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gnome-shell-communitheme-pr136` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Pull request merged**
