### PR TITLE
Darken app switchers text color & add a box-shadow to osd-panels

### PR DESCRIPTION
**Pull request by Feichtmeier**
Closes https://github.com/ubuntu/gtk-communitheme/issues/612

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gnome-shell-communitheme-pr237`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gnome-shell-communitheme-pr237` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
@madsrh just an idea
I've noticed that on the corner case "very dark desktop" the app switcher gets lost on the background:
peek 2018-07-07 10-35

After adding a shadow:
peek 2018-07-07 10-35_bs

really not sure about this though just an idea

**Comment by madsrh** [comment]
+1 for the shadow (if it looks fine on white/bright backgrounds too)

**Comment by Feichtmeier** [comment]
Okay another question for you and @clobrano and @godlyranchdressing 

How do you feel about adding this shadow to %osd_panel instead and so applying to both the OSDs and the alt tab switchers?

screenshot from 2018-07-07 11-50-00
screenshot from 2018-07-07 11-49-51

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gnome-shell-communitheme-pr237`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gnome-shell-communitheme-pr237` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
As Carlo and Mads like it and no-one complained I merge it and the rest didn't complain

**Pull request merged**
