### PR TITLE
Implemented new gnome-shell dock and top panel transparencies

### PR DESCRIPTION
**Pull request by clobrano**
- removed text and icon shadows
- unified transparency and color of dock and top panel
- added top border color (#2B2929) to dock to draw a separation from top
  panel
- on unmaximized windows: transparencies at 60%
- on maximized windows: transparencies at 40%

(This PR should produce a snap package to be tested before merge to master)

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gnome-shell-communitheme-pr125`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gnome-shell-communitheme-pr125` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
Here a snap to test @Luxamman proposal @madsrh @godlyranchdressing @Feichtmeier 
Transparent panel and dock in maximized mode don't look too bad, but with bright background it look like it is incomplete. Maybe reducing the transparency might work, but I'd like one feedback from you on this version first

**Comment by madsrh** [comment]
> Maybe reducing the transparency might work...

I was very skeptical about this, but gave it a try last night and I agree that with a slightly reduced transparency this might be good. It also makes the _huge block of darkness_ (as someone referred to earlier) less huge 😁

**Comment by Feichtmeier** [comment]
Tried this PR. I would not remote the shadow of the icons. 
On light backgrounds the icons are almost unreadable

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gnome-shell-communitheme-pr125`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gnome-shell-communitheme-pr125` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Luxamman** [comment]
Well I like it! 

- What I see is that the shadow is not well adjusted (looks like the shadow is falling left and on the right the transition is harder to see). Looks old fashioned when trying to make a 3D effect.
- And can we at least get rid of the shadow in max window mode? I know we need the shadow on light backgrounds, but only in window mode transparency. 
- Also, can we give the separation line on the top of the dock a little more color/dark? On certain backgrounds the line is not visible - but also only a little just to be there.

**Comment by clobrano** [comment]
> And if it fits here - the "current app" background on the dock behind the app-icon is not very visible

Does anybody know where that background is defined? I really could not find it

**Comment by clobrano** [comment]
I darkened the maxwindow mode a bit, and get rid of shadow in this use case. Also fixed text/icon shadow in unmaximixed mode

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gnome-shell-communitheme-pr125`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gnome-shell-communitheme-pr125` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
@clobrano 

it's in the _dock.scss file line 90
image

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gnome-shell-communitheme-pr125`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gnome-shell-communitheme-pr125` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by NusiNusi** [comment]
I like the transparency. Looks very nice!

**Comment by NusiNusi** [comment]
There was a reason for not having the same transparency for the dark headerbar, right?

**Comment by Feichtmeier** [comment]
You are talking about the GtkHeaderBar of each window?

**Comment by NusiNusi** [comment]
yes, the transparency of the topbar when windows a maximized looks so good it would be nice when the gtkheaderbar had the same transparency too. But i think there was a good reason for not doing it.
I would be happy when we could merge this PR

**Comment by Feichtmeier** [comment]
Let's wait until @Luxamman and @madsrh tried this snap

**Comment by Luxamman** [comment]
Thanks for the quick commitment, I just was trying the snap with different wallpapers and windows.
Quick thoughts: 

- Dock top-border little less dark in window mode (just a little less present, that's already fine adjustment) 
- Top bar and dock transparency could be a little more (more transparency) IMHO in window max mode, to let the wallpaper shine more thru and look less like the window header bar. Cause that is the point of that adjustment, to separate those elements.

Overall I like the look very much and the window management looks more finished and polished - thanks again!

**Comment by clobrano** [comment]
> There was a reason for not having the same transparency for the dark headerbar, right?

Correct. We dropped this option long time ago (look in the forum, for example), because it doesn't look good. Moreover I tried myself working on this PR and I confirm that opinion :grinning: 

> Top bar and dock transparency could be a little more (more transparency) IMHO in window max mode

Current 10% transparency it's ideal for removing shadows from the panel. With 20% (previous value), shadows were necessary IMHO.

> Dock top-border little less dark in window mode (just a little less present, that's already fine adjustment)

I tried several combinations, but I couldn't make this border change with window mode. I can find a compromise that is good with both max and unmax mode

**Comment by Feichtmeier** [comment]
Tried this PR again and hey this looks actually really good on maxed windows. Only on chrome it looks not that good, because chrome takes the gtk header color and makes it's own CSD headerbar. But as we didn't want to theme around specific apps this should be tested in "public" imho =) Great work @clobrano & @Luxamman

**Comment by Luxamman** [comment]
Thanks and I like it too, especially the window mode looks clean and modern (with the right wallpaper) - nice @clobrano  

> Current 10% transparency it's ideal for removing shadows from the panel. With 20% (previous value), shadows were necessary IMHO.

Before we test in public: 
If @clobrano is motivated I would love to try more transparency - maybe not 20% but maybe something in between? It's just on my second monitor (which is not that great) the contrast is not very visible between the bar and header bar - even on white wallpapers. Always hard to tell how much would be right without seeing it... can't give you a specific number, but I guess about 15%?

**Comment by clobrano** [comment]
> If @clobrano is motivated

Of course :wink:

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gnome-shell-communitheme-pr125`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gnome-shell-communitheme-pr125` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Luxamman** [comment]
Well, that was fast^^ Thanks @clobrano!
Looks good on most wallpapers, also the wallpaper still gives a little "character" to the max window mode. Maybe one or two % less, but we could decide that with a public test. 

One thing I like to ask you all about max windows: When a window is maximized, there is a dark border (and since Gnome update a light one whyever) on the top. Is it possible (and maybe looking more complete) to add a same border to the left window border, touching the dock?  
What do you think?

**Comment by clobrano** [comment]
> Looks good on most wallpapers, also the wallpaper still gives a little "character" to the max window mode. Maybe one or two % less, but we could decide that with a public test.

Agree on reducing it a bit, bright wallpapers shine too much to me.

> One thing I like to ask you all about max windows: When a window is maximized, there is a dark border (and since Gnome update a light one whyever) on the top. Is it possible (and maybe looking more complete) to add a same border to the left window border, touching the dock?
What do you think?

Is that what you meant?
image

If so, this is an effect of a bright box-shadow added to the headerbar only, when the window is maximized, and that makes the normal headerbar's border more evident. For this reason, I cannot add it to the the rest of the windows witch is borderless. However I don't think it would be a big issue, because main window is usually bright and the separation between the dock is quite visible as well.

**Comment by clobrano** [comment]
Agreed :+1:

**Comment by madsrh** [comment]
> Also, can we give the separation line on the top of the dock a little more color/dark? On certain backgrounds the line is not visible - but also only a little just to be there. And when in max window mode, can the line get even darker to fit the dark line presented by the max window?

I understand why you want the line to be there @Luxamman , but isn't this too much? I don't know if this just takes some getting used to, but it kind of "sticks out" IMO.
image

**Comment by Feichtmeier** [comment]
I don't like the separation of dock and top bar: it looks too much like layers above each other. Like big transparent silk tapes :anguished:

**Comment by madsrh** [comment]
>  like layers above each other...

However, I think that's the point 😉 Right @Luxamman ?

**Comment by Luxamman** [comment]
I know what you mean @madsrh - this is definitely something new to get used to and I'm okay to reduce the overall presence a little (making it more transparent) but I really don't want to let melt the bar and dock together - like stated out before.

They are not the same, have different meanings and the dock can even hide. So @Feichtmeier - I just wonder, why do you need to have them as one element? 

I never liked the both melting together, just makes sense to me because of the overall look and meaning. Also, the new separator line on top of the dock closes the max window gap... I guess I just like it to be clean and look complete^^

**Comment by Luxamman** [comment]
Understand - maybe because I mostly use other OS's to work :) 
But overall it is kind of more simple and clear - which should be an important point when designing for Ubuntu, because this should be a beginner and switcher friendly environment. 

So, can we try to reduce the separator line presents a little ( @clobrano ) and try it in the field and see how people react? For me it is very clear why I want that simple line (even if it is a little out of place, yeah), we also tried shadows in the beginning, but that was not working out like thought...

Big point for me here is also to work in window, and in max window mode. 
Are you okay with that?

**Comment by Feichtmeier** [comment]
I don't care that much. Just came here to place my skepticism =P
The PR is awesome overall anyways

**Comment by clobrano** [comment]
Let me try one more iteration. I was wondering whether the problem came from the fact that the line was popping up from the dock only, without any continuation on the panel. In the next snap I set the same line at the bottom of panel instead. This way I can even make it change in unmax and max mode.

Here some tests with wallpapers
image

image

Of course, with very dark background is invisible, but we would need something adaptive like in ElementaryOS
image

Finally, the in max mode, the vertical separation between window and dock comes from gtk-communitheme, so don't worry if you can't see it with this snap :)

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gnome-shell-communitheme-pr125`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gnome-shell-communitheme-pr125` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Luxamman** [comment]
@clobrano 
"Moved separation line from dock to panel" is not working for me, especially because in max window mode the lines add themselves to a bigger black line, in window mode the line makes the panel look stepping a little back. Would still prefer the short top-line on the dock.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gnome-shell-communitheme-pr125`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gnome-shell-communitheme-pr125` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by madsrh** [comment]
> Looks good - when will it be public?

Just press the merge button 😉

**Comment by Feichtmeier** [comment]
@clobrano @Luxamman great work this looks indeed very good!
screenshot from 2018-04-27 10-35-22

**Pull request merged**
