### PR TITLE
Revert box-shadow to match gtk windows

### PR DESCRIPTION
**Pull request by Feichtmeier**
This is the shadow of the GtkWindows @madsrh agreed on in the previous notification issue https://github.com/ubuntu/gnome-shell-communitheme/issues/89

### CODE REVIEW

**Comment by didrocks** [comment]
Reminder: please creating and using the *ubuntu/* org repo when you have rights (and I think you have it @Feichtmeier) so that snaps are created automatically for you: https://community.ubuntu.com/t/snapping-communitheme/4890/20

**Comment by godlyranchdressing** [comment]
@Feichtmeier Are we having the GTK3 and Shell notifications look the same? Because if we use the same WM shadow then we'll need to increase the margin, the shadow gets clipped past a certain point without increasing the margin to accommodate the shadow.

`box-shadow: 0 2px 2px transparentize(black, 0.75); margin: 8px;` (Current)

a

`box-shadow: 0 2px 5px transparentize(black, 0.75); margin: 8px;`

b

`box-shadow: 0 2px 5px transparentize(black, 0.75); margin: 12px;`

c

**Comment by Feichtmeier** [comment]
@godlyranchdressing that would be good propably. Why we took the GtkWindow shadow for shell notifications was because they act like another layer like a window above a window. Also the current shadow in master is hard to see at the left and right sides:
screenshot from 2018-04-19 16-29-24
This is the shadow from this commit here:
screenshot-20180419163124-1546x357
box-shadow: 0 3px 9px 1px transparentize(black, 0.5);

So this clipping is also present on gtkwindows atm? Then we could use this as a possibility to unify all layer drop shadows. I did not understand why they all differ in the first place? 
There are
GtkPopovers
GtkWindows
AppNotifications
Shell Notifications

Shouldn't they all have this shadow? (+ your margin)

**Comment by godlyranchdressing** [comment]
`box-shadow: 0 3px 9px 1px transparentize(black, 0.5);` needs even more of a margin than `box-shadow: 0 2px 5px transparentize(black, 0.75);`

I was a little worried that 12px for the notification margin might look kind of odd, but I just tested it out in Nautilus in maximized and maximized windows and it looks fine. Maybe we can just have all notifications follow `box-shadow: 0 2px 5px transparentize(black, 0.75);`? Everything but window shadows will have the same values that way. I'll make a PR for the GTK3 theme.

Window shadows don't have the clipping problem, but I do think that windows should have heavier shadows than everything else.

**Comment by madsrh** [comment]
Awesome work guys!

**Comment by Feichtmeier** [comment]
I remember that @clobrano and @madsrh are fans of big and wide shadows.
There is some bleeding with
box-shadow: 0 2px 5px transparentize(black, 0.75);
image

I am super annoying and say let's go with
box-shadow: 0 3px 9px 1px transparentize(black, 0.5);
image
I also can't see the clipping :( Which margin would I need for this shadow?

**Comment by godlyranchdressing** [comment]
@Feichtmeier The Shell notifications have no weird clipping issue, GTK3 notifications do. I'd just leave the margin as is and change the box-shadow values.

**Comment by Feichtmeier** [comment]
@godlyranchdressing oh sorry, it's getting late... 
Ah now I understand your argumentation xD 
Alright. I merge this then and maybe we could open another issue to unify all the shadows a bit

**Comment by Feichtmeier** [comment]
Do you know how to remove this bleed out when pressed though? This persists in every possible version and I just realized while we spoke here that it is there

**Comment by godlyranchdressing** [comment]
@Feichtmeier What bleed? Sorry. Unlike the others I'm the AST timezone :laughing:

**Comment by Feichtmeier** [comment]
@godlyranchdressing ah nice, good to know :)
There is a small edge bleed when you press the button:
peek 2018-04-19 23-41

**Comment by godlyranchdressing** [comment]
@Feichtmeier I remember running into that issue really long ago but I can't remember how to fix it. I think something like `box-shadow: inset 0 0 0 1px $approrpriate_border_variable` _might_ fix it. I don't know what causes it, I just chalk it up to being an annoying aliasing problem. 

You can always merge and I can try at it at some point.

**Comment by Feichtmeier** [comment]
Alright. Let's get back to it in some weeks when we hopefully only fix bugs! :)

**Comment by Feichtmeier** [comment]
@godlyranchdressing hmmm could you look it up again? how to fix this border bleed? It really looks shitty

**Comment by Feichtmeier** [comment]
@godlyranchdressing ok fixed it! Never mind

**Comment by godlyranchdressing** [comment]
@Feichtmeier really? What was the reason for the background?

**Comment by Feichtmeier** [comment]
@godlyranchdressing no idea about the reason but it needs and extra
.notification-button {
..........
&:active {
        background-color: rgba(0, 0, 0, 0.26);
        color: rgba(0, 0, 0, 0.87);
        border-radius: 0 0 $medium_radius $medium-radius; <------------
      }

peek 2018-04-26 22-35

**Comment by godlyranchdressing** [comment]
I guess it was kind of drawing another layer over the undo button that had to be curved to match the button's radius. Or something.

**Comment by Feichtmeier** [comment]
@godlyranchdressing what do you think of slightly transparent on hover

screenshot from 2018-04-26 22-46-39
screenshot from 2018-04-26 22-46-26

**Comment by Feichtmeier** [comment]
@madsrh it should be an indicator that you've hovered above it - please discuss this in the PR =D
https://github.com/ubuntu/gnome-shell-communitheme/pull/136

**Pull request merged**
