### PR TITLE
Changed alpha values to panel and dash to bring back transparency

### LINKED ISSUE #35: Top panel should be transparent when no window is close to it

### PR DESCRIPTION
**Pull request by clobrano**
closes #35

### CODE REVIEW

**Comment by godlyranchdressing** [comment]
Are we really going for complete transparency?

**Comment by clobrano** [comment]
I am not a big fan of the GNOME transparency level, but I'll post here some mockups so that we can find an agreement :)

**Comment by clobrano** [comment]
Here are some tests with various transparency levels. I like best the 0.9 level of transparency

https://paper.dropbox.com/doc/Top-panel-transparency-sq2gNcHVLLGWy7ctEMDgO?_tk=share_copylink

**Comment by galgalesh** [comment]
Wow, that's very transparant :laughing:

It does make my screen look bigger though, so that's good!

image

Is it intentional that the shadow persists and that the launcher has a black line?

**Comment by galgalesh** [comment]
Also, the google chrome icon seems to have a weird shadow, but I'm not sure if that's a communitheme or a chrome issue:

image

**Comment by didrocks** [comment]
The shadow is part of a shell styling IIRC (something we removed from the ubuntu theme)

**Comment by clobrano** [comment]
> Also, the google chrome icon seems to have a weird shadow, but I'm not sure if that's a communitheme or a chrome issue:

I added an icon shadow, does it look weird on chrome only?

> The shadow is part of a shell styling IIRC (something we removed from the ubuntu theme)
I'll have a look at that too

**Comment by clobrano** [comment]
What do you think about this PR, can we merge it, or does it need more adjustments?

**Comment by clobrano** [comment]
With last commits, this should close #43

**Comment by galgalesh** [comment]
image

\o/

**Comment by clobrano** [comment]
> Sorry for letting this hang for so long. Feel free to ping me or other people privately if I take too long ;)

No worries, I just didn't want to merge myself, because 4 eyes are better than 2, but I'm happy that today is merge day 😄

**Pull request merged**
