### PR TITLE
Lighten up osd border

### PR DESCRIPTION
**Pull request by Feichtmeier**
As a possible solution to https://github.com/ubuntu/gnome-shell-communitheme/issues/96

I would really love to try this on all your machines =D

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gnome-shell-communitheme-pr123`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gnome-shell-communitheme-pr123` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
Yeah I think this is a pretty solid solution. I generally like the white shell but it feels very un-ubuntu (what a word...)
The transparent white borde looks sharp and modern imho. As @godlyranchdressing suggested we could generally work on the white shell, which would only be "activated" if we really want to by adding the variable to common.scss.

**Comment by madsrh** [comment]
>  If @madsrh decides to keep the dark popovers...

I don't want to take that decision 😨 I'm a bit torn.

Anyway, @Feichtmeier I tried the PR123 and while I think it's a win for useabilty as it separates everything nicely and _fixes the issue_, I don't think it looks quite as good. There's a lot of lines in the top of the screen and it looks IMHO a bit messy. Didn't we start with a darker version back in november? 🤔 Something likethe dark version @godlyranchdressing is [using in United](https://cn.pling.com/img/3/f/b/5/5e413ac799a49843029720b4fe63ed577363.jpg)?

**Comment by Feichtmeier** [comment]
ok ok ok @madsrh 
How about this:

whiterborder02
whiterborder01

That's 
$osd_borders_color: transparentize(white, 0.85);
So a bit lighter, yet still better than current master

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gnome-shell-communitheme-pr123`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gnome-shell-communitheme-pr123` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by NusiNusi** [comment]
So we won't try a bright version of the popovers?

**Comment by Feichtmeier** [comment]
We will, but as @godlyranchdressing suggested, we could just include both a dark and light version and just toggle from light to dark with 1 variable. But it's still a long way (atleast for me) to a good looking bright theme. Also, @luxamman was not very exited about the light shell. So this PR is about a bright, transparent border.

**Comment by Feichtmeier** [comment]
@madsrh how about merging this second version above and see how it works out? We can change it back in a breeze =)

**Pull request merged**
