### PR TITLE
Use light colors for dialog windows

### PR DESCRIPTION
**Pull request by godlyranchdressing**
Uses light colors taken from the gtk theme for things like the shutdown dialog, brightness/volume popup and network manager dialog (click select network under wifi menu)
@madsrh @Luxamman

### CODE REVIEW

**Comment by clobrano** [comment]
The button bottom border looks too dark 

image

However I am not really convinced by this change, probably because the fact that the shell fade to dark  tones when this pop ups appear clashes a with this brightness

**Comment by Feichtmeier** [comment]
@godlyranchdressing I like it! Not much arguments despite -> unity8 

But no matter if we change it to white, does anyone know how to change those ugly (imho) buttons to flat? Luxamman wanted to flatten them all in shell and me... too! :dancer: 
If we would flatten them that ugly border should not be a problem since it's nonexistent then

**Comment by clobrano** [comment]
My understanding was that gnome shell buttons should look this way (#44), have I missed something?

**Comment by Feichtmeier** [comment]
@clobrano most buttons look perfectly (buttons in popovers)

There are only two buttons left that look "not flat" an pretty unthemed to me:
- the cancel button in GDM/lock screen -> where the hell is this guy in the theme file? :cry: 
- the buttons of shell dialogs -> no change works for me
peek 2018-05-01 19-09

Luxamman wanted flatter shell buttons here: https://community.ubuntu.com/t/mockups-new-design-discussions/1898/250
I already changed the "clear all notifications" button to flat in the calendar, but I cant find those two buttons I listed

**Comment by Feichtmeier** [comment]
Wow! Stunning! 
Could we please try this?  @clobrano @madsrh

**Comment by clobrano** [comment]
@godlyranchdressing if you could add this branch under ubuntu name repository also non developers could try it out with snaps

**Comment by godlyranchdressing** [comment]
<sup>am i doing this right

**Pull request closed without merging**
