### PR TITLE
Use Suru style user icon in GDM

### PR DESCRIPTION
**Pull request by nana-4**
Here is the screenshot:

image

There seems to be no effect with the user selection image:

image

Closes Ubuntu/gtk-communitheme#129

### CODE REVIEW

**Comment by galgalesh** [comment]
Hm I get an empty profile picture when I build this and reboot.. :thinking: 

Can you reproduce this?

**Comment by nana-4** [comment]
I tested on VM, Ubuntu 17.10, and both `Ubuntu Communitheme` & `Ubuntu Communitheme on Xorg`, but I couldn't reproduce that. :(

As you probably know, to see the new icon, you have to select the icon from the Settings app:

image

**Comment by galgalesh** [comment]
I took another look at this, the icon on the lock screen is now correct, but the icon on the "login" screen right after you boot is now empty.

**Comment by galgalesh** [comment]
# Lock screen
image

# Login screen

image

# Account

image

**Comment by nana-4** [comment]
Now I could reproduce that by replacing default gnome-shell theme to Communitheme.

@galgalesh I have one question; Hasn't the **background gradient** also disappeared on your **login screen**? Like the screenshot:

image

If so, we will need fixes for those assets as well.

**Comment by nana-4** [comment]
Updated. Please test whether the icon is displayed on your login screen as well.

**Comment by clobrano** [comment]
It's not working for me. I lost both icon and gradient

**Comment by nana-4** [comment]
I don't touch the gradient at all in this PR, but it's very strange to lost the icon even with latest commit...
I would like to know if other people can reproduce that.

@galgalesh Could you please test it with the new commit?

**Comment by clobrano** [comment]
@nana-4 have you seen if testing with a VM is reliable? If so, I could try again with that

**Comment by nana-4** [comment]
So sorry... I overlooked the way in `update-alternatives --install`. Instead I compiled the theme to `/usr/share/gnome-shell/gnome-shell-theme.gresource` in order to see the theme on the "login" screen.

I could reproduce the empty icon on the "login" screen with `update-alternatives --install`, but I noticed the "gradient" and "arrow icons" were also gone on the "login" screen.
image
image

I believe these are the same cause as the empty icon, but I couldn't figure out a workaround, except to compile the theme to `/usr/share/gnome-shell/gnome-shell-theme.gresource`. Any ideas?

**Comment by Feichtmeier** [comment]
@didrocks  this is the  PR I talked about on the other issue and the hub!
I invited you to the PM where I asked that questions to marco from  your working place :D So after getting the infos from that PM maybe you can answer in here about (hopefully) a solution

**Comment by didrocks** [comment]
As told, we can't compile the resources to it. I'll go to it once we switch to cosmic, as I don't have the time to look at it right now, but I guess the issue is related to the snap, as we don't have exported the variable there.

The icon is in the suru icon set, correct and keep the original name? If so, you shouldn't need to do anything once this is fixed (as we are going to ship a deb for cosmic, this isn't a problem for now).

**Comment by Feichtmeier** [comment]
This also occurs on a not snap installation via ninja and 
update-alternatives --install /usr/share/gnome-shell/theme/gdm3.css gdm3.css /usr/share/gnome-shell/theme/communitheme/gnome-shell.css 15
If I understand you correctly: this is fixed in cosmic once when the theme is used as default from within a deb anyways?

Yes the icon(s) is in the suru icon set. This PR is only about the user icon but the status bar icons are also wrong at login

**Comment by didrocks** [comment]
Interesting that it's happening on a ninja install, it should pick it as the expected place. I'll have a look anyway once we move forward with definitive name.

Just open an issue for tracking and remind me about it if I forget ;)
That's why we shouldn't merge this PR: it's a global issue on the gdm session (not picking the right icon theme), and shouldn't be hacked on the css.

**Comment by Feichtmeier** [comment]
Alright, I will start moving the few left issues to the gtk repo. I think that's faster manually since they are... 11 ? in numbers

**Comment by Feichtmeier** [comment]
Is there a certain time window (for example wait for code to be migrated first) to migrate the issues or can I start right away?

**Comment by didrocks** [comment]
Oh please, feel free to start right away. It will be less work for me even :) We just need to ensure we monitor this repo to move them if new ones are opened until we move, that's it.

**Pull request closed without merging**
