### PR TITLE
Fix the hotplug notification hover button background

### PR DESCRIPTION
**Pull request by Feichtmeier**
Fixed with the help of the awesome @nana-4  =)

screenshot from 2018-04-13 19-45-43

### CODE REVIEW

**Comment by Feichtmeier** [comment]
@nana-4 or @godlyranchdressing  could you review the code? @clobrano can't atm

**Comment by Feichtmeier** [comment]
@clobrano could you review the code and I merge it with rebase when you are ok with it? :)

**Comment by clobrano** [comment]
Sorry, as I said I won't be able to test anything until next Thursday

**Comment by Feichtmeier** [comment]
Ah okay sorry, didn't keep up with the calendar day :dancer:

**Comment by godlyranchdressing** [comment]
Looks alright to me. I made the shadow match the notification shadow from the GTK3 theme and just used some scss instead of css

**Comment by Feichtmeier** [comment]
Could you resolve the conflicts as a final step? I did not understand every line to 100% so it would be safer if you would resolve it instread of me.

**Comment by godlyranchdressing** [comment]
@Feichtmeier no problem. I didn't notice that there were conflicts or I'd have done it already.

**Comment by Feichtmeier** [comment]
@godlyranchdressing oh you changed the shadow of notification :O I thought it would be good to have the same shadow as windows.

**Pull request merged**
