### PR TITLE
White notifications & transparent white overview window clone border

### PR DESCRIPTION
**Pull request by Feichtmeier**
White notifications as a solution to the current readability problem of dark notifications on the dark GTK3 headerbars as discussed here: https://github.com/ubuntu/gnome-shell-communitheme/issues/89

### CODE REVIEW

**Comment by Feichtmeier** [comment]
@nana-4 @godlyranchdressing @clobrano 
There is a minor glitch which I can not fix - in the upper left corner of the notification there is some thing... bleeding out of the radius. Help would be appreciated :O

**Comment by clobrano** [comment]
Uhm, how do o

**Comment by clobrano** [comment]
Closed by mistake

**Comment by Feichtmeier** [comment]
Sure - I did use this shadow because this is the exact same shadow as used in GtkPopover menus. Some implementation screenshots incoming soon

**Comment by Feichtmeier** [comment]
A)     box-shadow: 0 2px 5px 2px transparentize(black, 0.75);
screenshot from 2018-04-03 19-36-26
screenshot from 2018-04-03 19-36-32

B)     box-shadow: 0 2px 5px 6px transparentize(black, 0.75);
screenshot from 2018-04-03 19-39-56
screenshot from 2018-04-03 19-40-02

Everything else is really too much imho. 
My preference would be the current one or A)

**Comment by clobrano** [comment]
Yeah, I like big shadows, but I think you're right, A is ok
@madsrh what do you think about that?

**Comment by Feichtmeier** [comment]
C)     box-shadow: 0 2px 7px 4px transparentize(black, 0.75);
screenshot from 2018-04-03 19-53-04
screenshot from 2018-04-03 19-53-08

**Comment by clobrano** [comment]
The shadow of the windows is in window decoration

https://github.com/ubuntu/gtk-communitheme/blob/07aedd3678d81caff9aa13573e9f8d24fbd337ba/Communitheme/gtk-3.0/_common.scss#L4546

**Comment by Feichtmeier** [comment]
Thanks - added the D) option for consistency.
I would  vote for D). It makes sense: if you stack windows above each other you have shadow and when you stack a notification above a window you have the same shadow

**Comment by madsrh** [comment]
D looks good to me - it really pops

**Comment by Feichtmeier** [comment]
D) is now commited + transparent white border as suggested by nana in https://github.com/ubuntu/gtk-communitheme/issues/289

screenshot from 2018-04-03 23-35-12

**Comment by Feichtmeier** [comment]
Increased close button size:
@madsrh @nana-4 is this okay for you?

screenshot from 2018-04-04 16-34-29

**Comment by clobrano** [comment]
wasn't the close button centered at the corner of the window (real question, can't check now)?

**Comment by Feichtmeier** [comment]
I did not change this one, maybe this looks different now because the border changed

**Comment by madsrh** [comment]
👍

**Comment by Feichtmeier** [comment]
I just realized that I can merge it myself - waiting for @clobrano @godlyranchdressing and/or @nana-4 to +1 the changes, since you allready raised your thumb xD

**Comment by nana-4** [comment]
@Feichtmeier +1 Of cause! :D

**Comment by Feichtmeier** [comment]
@clobrano I believe this is an "illusion" because the border is a bit bigger now. Look, just to show you what I mean I decrease the border (without the shadow) to 1 px, and I think it is really centered at the edge:

screenshot from 2018-04-04 19-26-40

Other than that, I don't know where to change the X/Y of this button :( @nana-4 I need you again

**Comment by NusiNusi** [comment]
The white notifications look so beautiful! I would like to see the shell-menus in the same colors.

**Comment by clobrano** [comment]
@Feichtmeier yes I was talking about the corner of the highlight. The code it should be here

https://github.com/ubuntu/gnome-shell-communitheme/blob/fa639505f5d0a29a381386adfb2b9dc7bd2b5792/communitheme/gnome-shell-sass/_common.scss#L1216

**Comment by Feichtmeier** [comment]
Ahh cool thanks @clobrano . This is ok?:

screenshot from 2018-04-04 19-39-53

That's 5px border and 13px overlay

**Comment by nana-4** [comment]
> I think it is really centered at the edge

I agree.

@clobrano Maybe with thin lines of X, I guess it won't bother you. What do you think?

**Comment by clobrano** [comment]
> Ahh cool thanks @clobrano . This is ok?

Perfect :+1:

**Comment by madsrh** [comment]
It seems the the buttons are still dark. Should I open an issue for this @Feichtmeier ? [This one](https://user-images.githubusercontent.com/15329494/38265524-7408104a-3776-11e8-9700-515767d45b18.png) you posted looked much better IMO

image

**Comment by Feichtmeier** [comment]
Oh, I can confirm this with my USB stick. Pretty strange. Tried different buttons but that's one I didn't try.
The one I posted is a different one you posted. I'll try to find it. Seems that there is a special part of code for only these USB stick notifications :dancer:

**Pull request merged**
