### PR TITLE
Initial changes

### PR DESCRIPTION
**Pull request by godlyranchdressing**
Not following any one mockup yet. Initial changes based on Unity 8.
Unity 8 launcher logo. Button, popover and panel mods. Minimize the use of orange.

### CODE REVIEW

**Comment by galgalesh** [comment]
Awesome!

The "apps" button is just an orange square, is the Ubuntu logo supposed to be sitting there? It doesn't seem to appear neither with humanity, nor with the suru icon theme..

image

**Comment by galgalesh** [comment]
I also get a one-pixel white line at the top of the screen on my second monitor. Are you able to reproduce this?

image

**Comment by godlyranchdressing** [comment]
Whoops. I forgot to bundle the icon with the theme and update the meson file. Everything should be working now.

**Comment by galgalesh** [comment]
Great, that fixed it, thanks!

**Pull request merged**
