### PR TITLE
Fix bug in app switcher

### PR DESCRIPTION
**Pull request by galgalesh**
A Japanese user ([sicklylife](https://launchpad.net/~sicklylife
)) sent me an issue with a patch to fix it. He doesn't have a Github account so he can't send it himself.

screencast

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gnome-shell-communitheme-pr205`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gnome-shell-communitheme-pr205` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
Ah nice we've forgotten that one when toggling between dark and light. Ty to that user!
But why increase the padding?

**Comment by galgalesh** [comment]
Normal padding for switcher-list is 8px, `outlined`-state padding was 6px, causing the weird jumping.

image

**Comment by Feichtmeier** [comment]
Great I test it later and merge it then thank you very much!!

**Pull request merged**
