### PR TITLE
Added activity indication color

### PR DESCRIPTION
**Pull request by clobrano**
Using Unity8 blue-ish color for volume slider and calendar day selector

### CODE REVIEW

**Comment by clobrano** [comment]
I refer to this page https://docs.ubuntu.com/phone/en/apps/design/building-blocks/activity-indicators

Here some pictures of the result
calendar

volume

**Comment by galgalesh** [comment]
This is indeed how it was done in Unity8. Another example: https://www.youtube.com/watch?v=_5poXYqTkgw

I actually like this change: I don't want to overdo the orange in the theme and I'm all for following in the footsteps of the Unity8 design, I feel as if a lot of thought was put into that. + Blue is a very commonly used color for focus (for example, github and upstream gnome use blue for focus)

However, I'd like to have the input of the design guys here. This is a massive diversion from the current design mockups. We might need to have a discussion if we're going to follow the Unity8 design or if we're going to diverge.

**Comment by galgalesh** [comment]
I think it's good to experiment with this "unity blue" for a while, so I want to merge this, but this PR has merge conflicts atm, I don't feel confident enough to fix them myself, can you fix them please?

**Comment by clobrano** [comment]
This should be ok now

**Pull request merged**
