### PR TITLE
Lighten button_bg_color

### LINKED ISSUE #160: Button flatness
@Feichtmeier mentioned that all buttons are going to be flat somewhere but I **really** don't think that this should extend to dialog buttons. The rest of the buttons being flat I can live with but these should pop out against the background.

---

The border around the notification clear all button is a little unnecessary:

bf
af

---

The button pressed effect needs to be updated.

dd

pra

### PR DESCRIPTION
**Pull request by godlyranchdressing**
Closes #160

4t

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Ah sorry I've seen the old gif in the issue. LGTM :+1:

**Comment by clobrano** [comment]
Why in the first and last picture "clear all" button is different? Which one is the one in this PR?
Moreover, shouldn't "shutdown, logout, settings" buttons be the same as "clear all"?

**Comment by Feichtmeier** [comment]
Normally I don't really like to compare the gtk theme too much to the shell but just for the logic: text-buttons could have a border like in the gtk theme
image
While btns with a symbolic icon don't need it that much because the wish to click an icon is higher than the desire to click text:
image

**Comment by Feichtmeier** [comment]
@godlyranchdressing @clobrano what about this? My personal opinion is still against this :-1: since it would be the only non flat button in all shell popups

**Comment by Feichtmeier** [comment]
Closing this as I don't feel like resolving the conflicts and this PR is some months old. Feel free to open a discussion about the shell popups on the gtk repo for either:

A) leave the popups flat
B) 
- remove box-pointers
- add box-shadow
- add 3D buttons EVERYWHERE in the popups

**Pull request closed without merging**
